### ISSUE TITLE
Use dashboard.out directly

### ISSUE THREAD

**Issue by BobLamarley** [adinhodovic/django-mixin#15]
Hello Adin,
I have a question, if i followed you're tutorial on you're website : https://hodovi.cc/blog/django-monitoring-with-prometheus-and-grafana/
I have'nt added `ExportModelOperationsMixin` on any of my  django models,
And i already configured a datasources.yaml file, that is mounted inside the grafana:
```
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s
```

Am i supposed to/ Can i import the json files in dashboard_out/ directly into the grafana website ?
Since my datasource has an uid called `prometheus`, i've just replaced all the `"uid": "$datasource"` to  `"uid": "prometheus"` but i think this isn't enough to make it work (I tried with this one: https://github.com/adinhodovic/django-mixin/blob/main/dashboards_out/django-overview.json ):
<img width="1465" alt="image" src="https://github.com/adinhodovic/django-mixin/assets/7857364/55b32fef-b621-4949-8c20-a2e430ee47d4">
